version: "3.8"

networks:
  monitoring:
    name: monitoring

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demopass
    ports:
      - "3306:3306"
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysqld-exporter:
    image: prom/mysqld-exporter
    container_name: mysqld-exporter
    command:
      - "--config.my-cnf=/etc/mysql_exporter/.my.cnf"
    volumes:
      - ./.my.cnf:/etc/mysql_exporter/.my.cnf:ro
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - monitoring  
