apiVersion: 1
groups:
  - orgId: 1
    name: down
    folder: alert.rules
    interval: 1m
    rules:
      - uid: test-down-alert
        title: Test Down Alert
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              disableTextWrap: false
              editorMode: code
              expr: 1 - up
              fullMetaSearch: false
              includeNullMetadata: true
              instant: true
              intervalMs: 1000
              legendFormat: '{{instance}}'
              maxDataPoints: 43200
              range: false
              refId: A
              useBackend: false
          - refId: C
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 0m
        annotations:
          description: Target with job {{ $labels.job }} and instance {{ $labels.instance }} is down (up = 0).
          summary: 'Target down: {{ $labels.instance }}'
        labels: {}
        isPaused: false
        notification_settings:
          receiver: Notification surcharge cpu
