apiVersion: 1
groups:
    - orgId: 1
      name: windows
      folder: alert.rules
      interval: 1m
      rules:
        - uid: deo55ijipo83ke
          title: Alerte Windows CPU
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: "100 - avg by (instance) (\r\n  rate(windows_cpu_time_total{mode=\"idle\"}[1m])\r\n) * 100"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          annotations: {}
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Notification surcharge cpu

