apiVersion: 1
groups:
    - orgId: 1
      name: linux
      folder: alert.rules
      interval: 1m
      rules:
        - uid: feo4yk092ldz4a
          title: High CPU usage (copy)
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 60
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                disableTextWrap: false
                editorMode: code
                expr: |
                    100 - (avg by (instance, job) (
                      rate(node_cpu_seconds_total{mode="idle"}[1m])
                    ) * 100)
                fullMetaSearch: false
                includeNullMetadata: true
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
                useBackend: false
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 90
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          annotations:
            description: Instance {{ $labels.job }} has high CPU usage.
            summary: CPU usage is above 70%
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Notification surcharge cpu

