version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
#      - GF_SECURITY_ADMIN_USER=admin
 #     - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://test.local/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/stockage/grafana
      - ./../Config/datasources/datasources.json:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./../Config/dashboards/:/etc/grafana/dashboards
      - ./../Config/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./../Config/alert/:/etc/grafana/provisioning/alerting/
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/var/stockage/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./../Config/prometheus.yml:/var/stockage/prometheus/prometheus.yml #partie avent les : emplacement du fichier de conf. apres les : emplacement du fichier dans le conteneur
      - prom_data:/var/stockage/prometheus-data
  nginx_reversproxy:
    image: nginx:latest
    ports:
      - '8080:8080'
    volumes:
      - ../Config/revers_proxy/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped


volumes:
  grafana-storage: {}
  prom_data: {}
  prometheus: {}
