version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/stockage/grafana
      - ./../Config/datasources/datasources.json:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./../Config/dashboards/:/etc/grafana/dashboards
      - ./../Config/dashboards/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./../Config/alert/:/etc/grafana/provisioning/alerting/
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/var/stockage/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./../Config/prometheus.yml:/var/stockage/prometheus/prometheus.yml #partie avent les : emplacement du fichier de conf. apres les : emplacement du fichier dans le conteneur
      - prom_data:/var/stockage/prometheus-data
  jira:
    image: atlassian/jira-software
    container_name: jira
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - jira_volume:/var/atlassian/application-data/jira

volumes:
  grafana-storage: {}
  prom_data: {}
  prometheus: {}
  jira_volume: {}
