version: "3.8"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/stockage/grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/var/stockage/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./../Config/prometheus.yml:/var/stockage/prometheus/prometheus.yml #partie avent les : emplacement du fichier de conf. apres les : emplacement du fichier dans le conteneur
      - prom_data:/var/stockage/prometheus-data

volumes:
  grafana-storage: {}
  prom_data: {}
  prometheus: {}
